### PR TITLE
Issue#130

### PR DESCRIPTION
**Pull request by sedrehman**
So issue 130 is done but task 132 had to be modified. So now a student can add their grades to their class if they made an appointment for that class. If a grade already exits then their new grade is appended to the previous. 

Students can also add grades for the class after claiming a slot from a tutor. This makes an appointment and prompts a user to enter any previous grades they they desire. 

test using student@buffalo.edu  and password= "Hello123!"

### CODE REVIEW

**Review by jechepenuk — COMMENTED** [review]
ignore

**Review by jechepenuk — CHANGES_REQUESTED** [review]
change input for exam grades to be 0-100

**Comment by sedrehman** [comment]
OK Jenny I only allowed input from 0 - 150 in case there are bonus points..

**Review by jechepenuk — APPROVED** [review]
perf

**Review by kesamercy — APPROVED** [review]

**Review by TKTre — APPROVED** [review]
Works well!  Maybe add placeholder text for the text box on the add grades page with the value "Enter your grade here" or something like that?

**Pull request merged**
