### PR TITLE
Issue#146 zoom meeting

### PR DESCRIPTION
**Pull request by TKTre**
Test at https://www-student.cse.buffalo.edu/CSE442-542/2020-spring/cse-442i/442TreTesting/cse442-semester-project-jalapenocrisp/ 

- Go to a tutor profile and click "Add/Edit Zoom Link"
- Follow instructions on the page
(ensure Zoom link verify function works)
- Log in to a student account and find the tutor from step 1
- Click the "Go to This Tutor's Zoom Meeting Room" 
- This button should redirect you to the Zoom Meeting Room you entered.  
[Also test Meaner Beaner (under CSE115) ad ensure it takes you to Elwyn's Personal Meeting Room]

### CODE REVIEW

**Review by jechepenuk — CHANGES_REQUESTED** [review]
i couldnt open the link in a new tab. if you add this it will work

onclick=" **window.open('http://google.com','_blank')**"
 
specifically the _blank portion solves this issue. you should also add this on the student side.

on the student side, you should add a check to see if the tutor's zoom id is null, and if it is do not display that button. we know its not a broken button, but the grader might not.

**Comment by TKTre** [comment]
Thanks for the feedback Jennie!  I totally forgot to add the null check on the student side like I meant to...whoops.  And thanks for the 'new tab' help!

**Comment by TKTre** [comment]
Changes that were requested were fixed!  Give it another look when you have a second.

**Review by jechepenuk — APPROVED** [review]
awesome!

**Review by kesamercy — APPROVED** [review]
Nice

**Review by sedrehman — APPROVED** [review]
looks good to me

**Pull request merged**
